gcc -o ack lib/main.c ack.s
gcc -o ackopt lib/main.c ackopt.s
gcc -o apply lib/main.c apply.s
gcc -o applyopt lib/main.c applyopt.s
gcc -o arith lib/main.c arith.s
gcc -o arithopt lib/main.c arithopt.s
gcc -o cadr lib/main.c cadr.s
gcc -o cadropt lib/main.c cadropt.s
gcc -o countup lib/main.c countup.s
gcc -o countupopt lib/main.c countupopt.s
gcc -o obj lib/main.c obj.s
gcc -o objopt lib/main.c objopt.s
gcc -o sum_loop lib/main.c sum_loop.s
gcc -o sum_loopopt lib/main.c sum_loopopt.s
gcc -o sumsqr lib/main.c sumsqr.s
gcc -o sumsqropt lib/main.c sumsqropt.s
gcc -o even lib/main.c even.s
gcc -o evenopt lib/main.c evenopt.s
gcc -o expt lib/main.c expt.s
gcc -o exptopt lib/main.c exptopt.s
gcc -o seq lib/main.c seq.s
gcc -o seqopt lib/main.c seqopt.s
gcc -o sort lib/main.c sort.s
gcc -o sortopt lib/main.c sortopt.s
gcc -o bst lib/main.c bst.s
gcc -o bstopt lib/main.c bstopt.s
gcc -o fenv lib/main.c fenv.s
gcc -o fenvopt lib/main.c fenvopt.s
gcc -o fib lib/main.c fib.s
gcc -o fibopt lib/main.c fibopt.s
gcc -o rr lib/main.c rr.s
gcc -o rropt lib/main.c rropt.s
gcc -o rw lib/main.c rw.s
gcc -o rwopt lib/main.c rwopt.s
gcc -o sort lib/main.c sort.s
gcc -o sortopt lib/main.c sortopt.s
