gcc -o bin/ack lib/main.c assembly/ack.s
gcc -o bin/ackopt lib/main.c assembly/ackopt.s
gcc -o bin/apply lib/main.c assembly/apply.s
gcc -o bin/applyopt lib/main.c assembly/applyopt.s
gcc -o bin/arith lib/main.c assembly/arith.s
gcc -o bin/arithopt lib/main.c assembly/arithopt.s
gcc -o bin/cadr lib/main.c assembly/cadr.s
gcc -o bin/cadropt lib/main.c assembly/cadropt.s
gcc -o bin/countup lib/main.c assembly/countup.s
gcc -o bin/countupopt lib/main.c assembly/countupopt.s
gcc -o bin/obj lib/main.c assembly/obj.s
gcc -o bin/objopt lib/main.c assembly/objopt.s
gcc -o bin/sum_loop lib/main.c assembly/sum_loop.s
gcc -o bin/sum_loopopt lib/main.c assembly/sum_loopopt.s
gcc -o bin/sumsqr lib/main.c assembly/sumsqr.s
gcc -o bin/sumsqropt lib/main.c assembly/sumsqropt.s
gcc -o bin/even lib/main.c assembly/even.s
gcc -o bin/evenopt lib/main.c assembly/evenopt.s
gcc -o bin/expt lib/main.c assembly/expt.s
gcc -o bin/exptopt lib/main.c assembly/exptopt.s
gcc -o bin/seq lib/main.c assembly/seq.s
gcc -o bin/seqopt lib/main.c assembly/seqopt.s
gcc -o bin/sort lib/main.c assembly/sort.s
gcc -o bin/sortopt lib/main.c assembly/sortopt.s

